Models/Categoria.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace simulacro.Models
{
    [Table("t_categoria")]
    public class Categoria{
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id {get; set;}
        public string nombre {get; set;}
        public ICollection<SolicitudCompra> solicitud {get; set;}
    }
}

Models/ErrorViewModel.cs
using System;

namespace simulacro.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/SolicitudCompra.cs
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace simulacro.Models
{
    [Table("t_solicitud")]
    public class SolicitudCompra{
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int id{get; set;}
        public string nombre{get; set;}
        public string foto{get; set;}
        public string descripcion{get; set;}
        public decimal precio{get; set;}
        public string celular{get; set;}
        public DateTime fecha{get; set;}
        public string lugar{get; set;}
        public string comprador{get; set;}
        public Categoria categoria {get; set;}

        public SolicitudCompra(){
            this.fecha = new DateTime();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using simulacro.Models;

namespace simulacro.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/SolicitudController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using simulacro.Models;
using simulacro.Data;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace simulacro.Controllers
{
    public class SolicitudController : Controller
    {
        private readonly ApplicationDbContext _context;
        public SolicitudController(ApplicationDbContext context)
        {
            _context = context;
        }

        public IActionResult Registrar(){
            var categorias = _context.DataCategorias.ToList();
            List<SelectListItem> items = categorias.ConvertAll(d => {
                return new SelectListItem(){
                    Text = d.nombre,
                    Value = d.Id.ToString(),
                    Selected = false
                };
            }); 
           ViewBag.items = items;
            return View();
        }

        [HttpPost]
        public IActionResult Registrar(SolicitudCompra solicitudCompra){
            if(ModelState.IsValid){
                _context.Add(solicitudCompra);
                _context.SaveChanges();
                return RedirectToAction("Listar");
            }
            return View(solicitudCompra);
        }

        public IActionResult Listar(){
            var solicitudes = _context.DataContactos.ToList();
            return View(solicitudes);
        }

    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - simulacro</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">simulacro</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Solicitud" asp-action="Registrar">Registrar Producto</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - simulacro - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Solicitud/Registrar.cshtml
@model SolicitudCompra
@{
    ViewData["Title"] = "Registro de Usuarios";
    List<SelectListItem> items = (List<SelectListItem>)ViewBag.items;
    
}
<h1>@ViewData["Title"]</h1>

<h1>REGISTRO DE PRODUCTO</h1>

<div asp-validation-summary="All" class="text-danger"></div>

<form asp-controller="Contacto" asp-action="Formulario" method="post">

    <div class="form-group">
        <label asp-for="nombre">NOMBRE: </label>
        <input type="text" asp-for="nombre" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="foto">FOTO: </label>
        <input type="text" asp-for="foto" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="descripcion">DESCRIPCIÓN: </label>
        <textarea type="text" asp-for="descripcion" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <label asp-for="precio">PRECIO: </label>
        <input type="text" asp-for="precio" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="celular">CELULAR: </label>
        <input type="text" asp-for="celular" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="lugar">LUGAR: </label>
        <input type="text" asp-for="lugar" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="comprador">COMPRADOR: </label>
        <input type="text" asp-for="comprador" class="form-control">
    </div>
    <div class="form-group">
        <label asp-for="categoria">CATEGORIA: </label>
         <div>
           @Html.DropDownList("datos" , items , "Selecciona tu categoria")
       </div>  
    <button class="btn btn-info">ENVIAR</button>

</form>